<?php

return [
    [
        "title" => "Minecraft ",
        "publisher" => "Mojang Studios",
        "publication_year" => '2011-11-18',
        "developers" => "Mojang Studios",
        "platforms" => ' Windows, iOS, Android, PlayStation 4',
        "pegi" => 7,
        "genre" => 'sandbox, survival',
        "rating" => 9.8,
        "thumbnail" => 'https://www.codiciprodotto.it/wp-content/uploads/2021/01/minecraft.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Grand Theft Auto V",
        "publisher" => "Rockstar Games",
        "publication_year" => '2013-10-13',
        "developers" => "Rockstar North",
        "platforms" => ' PlayStation 4, PlayStation 5, PlayStation 3, Xbox One, Xbox 360, Xbox Series X/S, Microsoft Windows',
        "pegi" => 18,
        "genre" => 'Action-adventure',
        "rating" => 9.9,
        "thumbnail" => 'https://www.gtabase.com/igallery/8501-8600/gta-v-cover-ps5-xbox-series-xs-8584-1920.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Red Dead Redemption 2",
        "publisher" => "Rockstar Games",
        "publication_year" => '2018-10-26',
        "developers" => "Rockstar Studios",
        "platforms" => '',
        "pegi" => 18,
        "genre" => 'Action-adventure',
        "rating" => 9.7,
        "thumbnail" => 'https://www.gtabase.com/igallery/4201-4300/RDR_2_Cover_PC-4213-1920.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "The Elder Scrolls V: Skyrim",
        "publisher" => "Bethesda Game Studios",
        "publication_year" => '2011-11-11',
        "developers" => "Bethesda Softworks",
        "platforms" => ' PlayStation 4, Xbox One, Nintendo Switch',
        "pegi" => 18,
        "genre" => 'Action role-playing',
        "rating" => 9.3,
        "thumbnail" => 'https://upload.wikimedia.org/wikipedia/en/1/15/The_Elder_Scrolls_V_Skyrim_cover.png',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Fortnite",
        "publisher" => "Epic Games",
        "publication_year" => '2017-05-16',
        "developers" => "Epic Games",
        "platforms" => 'Project xCloud, GeForce Now, PlayStation 5',
        "pegi" => 12,
        "genre" => 'Battle royale',
        "rating" => 8.4,
        "thumbnail" => 'https://gaming-cdn.com/images/products/2500/orig-fallback-v1/fortnite-pc-gioco-epic-games-cover.jpg?v=1645021449',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "World of Warcraft",
        "publisher" => "Blizzard Entertainment",
        "publication_year" => '2004-11-23',
        "developers" => "Blizzard Entertainmen",
        "platforms" => ' macOS, Microsoft Windows, Classic Mac OS',
        "pegi" => 18,
        "genre" => 'Massively multiplayer online role-playing',
        "rating" => 7.9,
        "thumbnail" => 'https://m.media-amazon.com/images/I/510Xjw4h8kS._AC_SY445_.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "The Last of Us",
        "publisher" => "Sony Computer Entertainment",
        "publication_year" => '2013-06-14',
        "developers" => "Naughty Dog",
        "platforms" => '',
        "pegi" => 18,
        "genre" => '',
        "rating" => 9.4,
        "thumbnail" => 'https://static.posters.cz/image/750/poster/the-last-of-us-key-art-i127761.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Super Mario 64",
        "publisher" => "Nintendo EAD",
        "publication_year" => '1996-06-14',
        "developers" => "Nintendo",
        "platforms" => '',
        "pegi" => 3,
        "genre" => '',
        "rating" => 8.0,
        "thumbnail" => 'https://upload.wikimedia.org/wikipedia/it/thumb/3/3e/Super_Mario_64.jpg/640px-Super_Mario_64.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Batman: Arkham City",
        "publisher" => "Warner Bros. Interactive Entertainment",
        "publication_year" => '2011-10-18',
        "developers" => "Rocksteady Studios",
        "platforms" => 'PlayStation 3, PlayStation 4, Xbox 360, Xbox One, Microsoft Windows, Wii U, macOS',
        "pegi" => 16,
        "genre" => 'Action-adventure',
        "rating" => 8.1,
        "thumbnail" => 'https://static.posters.cz/image/750/poster/batman-arkham-city-cover-i11510.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Half-Life 2",
        "publisher" => "Valve",
        "publication_year" => '2004-11-06',
        "developers" => "Valve",
        "platforms" => 'Windows,Xbox,Xbox 360,PlayStation 3',
        "pegi" => 18,
        "genre" => 'First-person shooter',
        "rating" => 8.1,
        "thumbnail" => 'https://www.gamerclick.it/immagini/videogame/Half_Life_2/cover/Half_Life_2-cover.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Mass Effect 2",
        "publisher" => "Electronic Arts",
        "publication_year" => '2010-01-16',
        "developers" => "BioWare",
        "platforms" => 'Microsoft Windows,Xbox 360,PlayStation 3',
        "pegi" => 18,
        "genre" => 'Action role-playing, third-person shooter',
        "rating" => 8.1,
        "thumbnail" => 'https://static.wikia.nocookie.net/masseffectitalia/images/4/4b/ME2_Soundtrack_Cover.png/revision/latest?cb=20141022104223&path-prefix=it',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Dark Souls",
        "publisher" => "Namco Bandai Games",
        "publication_year" => '2011-10-18',
        "developers" => "FromSoftware",
        "platforms" => 'PlayStation 4, Nintendo Switch, PlayStation 3, Xbox One, Xbox 360, Microsoft Windows',
        "pegi" => 16,
        "genre" => 'Action role-playing',
        "rating" => 8.1,
        "thumbnail" => 'https://upload.wikimedia.org/wikipedia/en/8/8d/Dark_Souls_Cover_Art.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Silent Hill 2",
        "publisher" => "Konami",
        "publication_year" => '2001-04-13',
        "developers" => "Team Silent",
        "platforms" => 'PlayStation 2,Xbox, Windows',
        "pegi" => 18,
        "genre" => 'Survival horror',
        "rating" => 8.1,
        "thumbnail" => 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/1057256e-383f-4417-a343-5eae9d369263/ddxi6lp-75cd791d-aa99-416f-806e-96b121b6270b.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzEwNTcyNTZlLTM4M2YtNDQxNy1hMzQzLTVlYWU5ZDM2OTI2M1wvZGR4aTZscC03NWNkNzkxZC1hYTk5LTQxNmYtODA2ZS05NmIxMjFiNjI3MGIucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.HuMGkht9C1nEkPghhz65U-Qj6MZcBPQB1Ug0oE4xzQg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Dota 2",
        "publisher" => "Valve",
        "publication_year" => '2013-09-25',
        "developers" => "Valve",
        "platforms" => 'Windowa',
        "pegi" => 16,
        "genre" => 'MOBA',
        "rating" => 8.1,
        "thumbnail" => 'https://e.snmc.io/lk/l/x/481cf50670f6cd67d8fa5a899c174284/5288890',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Halo: Combat Evolved",
        "publisher" => "Microsoft Game Studios",
        "publication_year" => '2001-11-05',
        "developers" => "Bungie",
        "platforms" => 'Xbox, Windows',
        "pegi" => 16,
        "genre" => 'First-person shooter',
        "rating" => 8.1,
        "thumbnail" => 'https://upload.wikimedia.org/wikipedia/en/8/80/Halo_-_Combat_Evolved_%28XBox_version_-_box_art%29.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "God of War",
        "publisher" => "Sony Interactive Entertainment",
        "publication_year" => '2011-10-18',
        "developers" => "Santa Monica Studio",
        "platforms" => 'Playstation 4',
        "pegi" => 18,
        "genre" => 'Action-adventure, hack and slash',
        "rating" => 8.1,
        "thumbnail" => 'https://upload.wikimedia.org/wikipedia/en/a/a7/God_of_War_4_cover.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "The Legend of Zelda: Ocarina of Time",
        "publisher" => "Nintendo",
        "publication_year" => '2011-10-18',
        "developers" => "Nintendo EAD",
        "platforms" => 'Nintendo 64',
        "pegi" => 3,
        "genre" => 'Action-adventure',
        "rating" => 8.1,
        "thumbnail" => 'https://www.staynerd.com/wp-content/uploads/ocarina_of_time_ft-img.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Tony Hawk's Pro Skater 2",
        "publisher" => "Activision",
        "publication_year" => '2000-09-19',
        "developers" => "Neversoft",
        "platforms" => 'iOS, Microsoft Windows, Game Boy Advance',
        "pegi" => 3,
        "genre" => 'Sports',
        "rating" => 8.1,
        "thumbnail" => 'https://assets-prd.ignimgs.com/2022/01/29/tony-hawk-pro-skater-2-button-edit-1643485674590.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "BioShock",
        "publisher" => "2K",
        "publication_year" => '2007-10-18',
        "developers" => "2K",
        "platforms" => 'Windows,Xbox 360, Playstation 3,',
        "pegi" => 16,
        "genre" => 'First-person shooter',
        "rating" => 8.1,
        "thumbnail" => 'https://upload.wikimedia.org/wikipedia/en/6/6d/BioShock_cover.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
    [
        "title" => "Journey",
        "publisher" => "Sony Computer Entertainment",
        "publication_year" => '2013-04-11',
        "developers" => "Thatgamecompany",
        "platforms" => 'Playstation 3, Playstation 4, Windows',
        "pegi" => 3,
        "genre" => 'Adventure, art game',
        "rating" => 8.1,
        "thumbnail" => 'https://s3.amazonaws.com/prod-media.gameinformer.com/styles/product_box_art/s3/2019/08/07/6cf0190d/journey.jpg',
        "early_access" => 0,
        "description" => 'lorem ipsum dolor sit am'
    ],
];